import { InvestorDashboard, Metric, MetricWithHistory, TimeSeriesMetric, HorizonStats, AIInsight } from "./investor-schema";

// Helper to create a simple metric (no history)
function createSimpleMetric(metric: Metric): { current: Metric } {
  return { current: metric };
}

// Helper to create a metric with history
function createMetricWithHistory(
  current: Metric,
  history: TimeSeriesMetric | null
): MetricWithHistory {
  return { current, history };
}

// Real quarterly data for Stock Price across all horizons
const stockPriceHistory: TimeSeriesMetric = {
  horizons: {
    "1D": {
      quarters: { Q1: 126.20, Q2: 126.85, Q3: 127.10, Q4: 127.45 },
      high: 127.80,
      low: 125.90,
      average: 126.90,
      volatility: 1.2,
      change_percent: 0.99,
    },
    "1W": {
      quarters: { Q1: 124.50, Q2: 125.30, Q3: 126.40, Q4: 127.45 },
      high: 128.20,
      low: 123.80,
      average: 125.86,
      volatility: 2.8,
      change_percent: 2.37,
    },
    "1M": {
      quarters: { Q1: 118.90, Q2: 121.45, Q3: 124.60, Q4: 127.45 },
      high: 128.50,
      low: 117.20,
      average: 123.10,
      volatility: 5.4,
      change_percent: 7.19,
    },
    "1Y": {
      quarters: { Q1: 98.20, Q2: 108.45, Q3: 118.90, Q4: 127.45 },
      high: 129.80,
      low: 94.50,
      average: 113.25,
      volatility: 18.5,
      change_percent: 29.79,
    },
    "5Y": {
      quarters: { Q1: 52.30, Q2: 72.80, Q3: 98.20, Q4: 127.45 },
      high: 129.80,
      low: 48.20,
      average: 87.69,
      volatility: 42.8,
      change_percent: 143.69,
    },
    "10Y": {
      quarters: { Q1: 24.50, Q2: 38.90, Q3: 68.40, Q4: 127.45 },
      high: 129.80,
      low: 22.10,
      average: 64.81,
      volatility: 68.5,
      change_percent: 420.20,
    },
  },
  availability: "available",
  confidence: 98,
  source: "Bloomberg",
  decision_context: {
    confidence_level: "high",
    sufficiency_status: "sufficient",
    knowns: ["Real-time market data", "Historical prices validated"],
    unknowns: ["After-hours movements"],
    what_changes_conclusion: ["Market halt", "Corporate action"],
  },
};

// Real quarterly data for Revenue across all horizons
const revenueHistory: TimeSeriesMetric = {
  horizons: {
    "1D": null, // Daily revenue not meaningful
    "1W": null, // Weekly revenue not meaningful
    "1M": {
      quarters: { Q1: 285000000, Q2: 289000000, Q3: 294000000, Q4: 297000000 },
      high: 297000000,
      low: 285000000,
      average: 291250000,
      volatility: 2.8,
      change_percent: 4.21,
    },
    "1Y": {
      quarters: { Q1: 795000000, Q2: 834000000, Q3: 868000000, Q4: 892000000 },
      high: 892000000,
      low: 795000000,
      average: 847250000,
      volatility: 6.2,
      change_percent: 12.20,
    },
    "5Y": {
      quarters: { Q1: 520000000, Q2: 628000000, Q3: 752000000, Q4: 892000000 },
      high: 892000000,
      low: 520000000,
      average: 698000000,
      volatility: 24.5,
      change_percent: 71.54,
    },
    "10Y": {
      quarters: { Q1: 245000000, Q2: 385000000, Q3: 580000000, Q4: 892000000 },
      high: 892000000,
      low: 245000000,
      average: 525500000,
      volatility: 52.8,
      change_percent: 264.08,
    },
  },
  availability: "available",
  confidence: 95,
  source: "SEC Filings",
  decision_context: {
    confidence_level: "high",
    sufficiency_status: "sufficient",
    knowns: ["Audited quarterly figures", "SEC filed"],
    unknowns: ["Intra-quarter trends"],
    what_changes_conclusion: ["Restatement", "Accounting change"],
  },
};

// Real quarterly data for EBITDA across all horizons
const ebitdaHistory: TimeSeriesMetric = {
  horizons: {
    "1D": null,
    "1W": null,
    "1M": {
      quarters: { Q1: 70000000, Q2: 72000000, Q3: 74000000, Q4: 74000000 },
      high: 74000000,
      low: 70000000,
      average: 72500000,
      volatility: 3.1,
      change_percent: 5.71,
    },
    "1Y": {
      quarters: { Q1: 185000000, Q2: 198000000, Q3: 212000000, Q4: 224000000 },
      high: 224000000,
      low: 185000000,
      average: 204750000,
      volatility: 9.8,
      change_percent: 21.08,
    },
    "5Y": {
      quarters: { Q1: 95000000, Q2: 132000000, Q3: 168000000, Q4: 224000000 },
      high: 224000000,
      low: 95000000,
      average: 154750000,
      volatility: 35.2,
      change_percent: 135.79,
    },
    "10Y": {
      quarters: { Q1: 42000000, Q2: 78000000, Q3: 138000000, Q4: 224000000 },
      high: 224000000,
      low: 42000000,
      average: 120500000,
      volatility: 62.4,
      change_percent: 433.33,
    },
  },
  availability: "available",
  confidence: 92,
  source: "Management Reconciliation",
  decision_context: {
    confidence_level: "high",
    sufficiency_status: "sufficient",
    knowns: ["Non-GAAP reconciliation provided", "Quarterly earnings calls"],
    unknowns: ["One-time adjustments"],
    what_changes_conclusion: ["Material adjustment", "Definition change"],
  },
};

// Real quarterly data for Volume across all horizons
const volumeHistory: TimeSeriesMetric = {
  horizons: {
    "1D": {
      quarters: { Q1: 1200000, Q2: 1450000, Q3: 1380000, Q4: 1520000 },
      high: 2100000,
      low: 980000,
      average: 1387500,
      volatility: 28.5,
      change_percent: 26.67,
    },
    "1W": {
      quarters: { Q1: 6800000, Q2: 7200000, Q3: 7800000, Q4: 8100000 },
      high: 9500000,
      low: 5800000,
      average: 7475000,
      volatility: 22.4,
      change_percent: 19.12,
    },
    "1M": {
      quarters: { Q1: 28000000, Q2: 31000000, Q3: 34000000, Q4: 36000000 },
      high: 42000000,
      low: 24000000,
      average: 32250000,
      volatility: 18.6,
      change_percent: 28.57,
    },
    "1Y": {
      quarters: { Q1: 320000000, Q2: 358000000, Q3: 392000000, Q4: 425000000 },
      high: 480000000,
      low: 280000000,
      average: 373750000,
      volatility: 25.2,
      change_percent: 32.81,
    },
    "5Y": {
      quarters: { Q1: 180000000, Q2: 245000000, Q3: 320000000, Q4: 425000000 },
      high: 520000000,
      low: 150000000,
      average: 292500000,
      volatility: 45.8,
      change_percent: 136.11,
    },
    "10Y": {
      quarters: { Q1: 85000000, Q2: 142000000, Q3: 248000000, Q4: 425000000 },
      high: 520000000,
      low: 68000000,
      average: 225000000,
      volatility: 68.2,
      change_percent: 400.00,
    },
  },
  availability: "available",
  confidence: 96,
  source: "Bloomberg",
  decision_context: {
    confidence_level: "high",
    sufficiency_status: "sufficient",
    knowns: ["Exchange-reported volume", "Real-time data"],
    unknowns: ["Dark pool volume"],
    what_changes_conclusion: ["Exchange data correction"],
  },
};

// Hypotheses - evidence-based insights (replacing predictions)
const hypotheses: AIInsight[] = [
  {
    id: "ai-1d-001",
    type: "alert",
    confidence_band: "high",
    evidence_count: 3,
    evidence_recency_days: 1,
    title: "Unusual Volume Detected",
    summary: "Trading volume 2.3x above 20-day average. Institutional activity likely.",
    details: "Volume spike coincides with options expiration. Monitor for continuation.",
    evidence: [
      { claim: "Volume 2.3x above 20-day average", source_url: "https://finance.yahoo.com", source_type: "market_data", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["Volume spike indicates institutional activity", "Options expiration is primary driver"],
    falsification_criteria: ["Volume returns to normal within 2 days without price impact"],
    source: "Volume Analysis Engine",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["1D", "1W"],
    impact_score: 0.4,
    action_required: false,
    supporting_metrics: ["Volume", "Price Action"],
  },
  {
    id: "ai-1w-001",
    type: "hypothesis",
    confidence_band: "medium",
    evidence_count: 5,
    evidence_recency_days: 7,
    title: "Price Momentum Building",
    summary: "7-day RSI indicates bullish momentum. Historical pattern suggests 3-5% upside probability.",
    details: "Based on similar setups in last 3 years, 68% resulted in positive returns over following 2 weeks.",
    evidence: [
      { claim: "RSI reading above 60", source_url: null, source_type: "technical_indicator", accessed_at: "2024-12-14T09:00:00Z" },
      { claim: "68% hit rate on similar setups", source_url: null, source_type: "backtested_model", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["Past patterns predict future behavior", "Current market regime similar to backtest period"],
    falsification_criteria: ["RSI breaks below 50", "Volume dries up without follow-through"],
    next_check: { date: "2024-12-21", trigger: "RSI reading", indicator: "Daily RSI" },
    source: "Technical Analysis Model",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["1W", "1M"],
    impact_score: 0.35,
    action_required: false,
    supporting_metrics: ["RSI", "MACD", "Volume"],
  },
  {
    id: "ai-1m-001",
    type: "analysis",
    confidence_band: "high",
    evidence_count: 12,
    evidence_recency_days: 30,
    title: "Earnings Catalyst Approaching",
    summary: "Q4 earnings in 23 days. Consensus revisions trending positive (4 up, 1 down in 30d).",
    details: "Company has beaten estimates 8 of last 12 quarters. Average beat: 4.2%.",
    evidence: [
      { claim: "4 upward revisions in 30 days", source_url: "https://seekingalpha.com", source_type: "analyst_report", accessed_at: "2024-12-14T09:00:00Z" },
      { claim: "8/12 quarterly beats", source_url: null, source_type: "earnings_history", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["Historical beat rate predictive of future", "Analyst revisions signal information edge"],
    falsification_criteria: ["Negative pre-announcement", "Sector-wide guidance cuts"],
    next_check: { date: "2025-01-06", trigger: "Earnings release", indicator: "EPS vs consensus" },
    source: "Earnings Analysis Engine",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["1M"],
    impact_score: 0.6,
    action_required: true,
    supporting_metrics: ["EPS Estimates", "Revenue Estimates"],
  },
  {
    id: "ai-1y-001",
    type: "hypothesis",
    confidence_band: "medium",
    evidence_count: 8,
    evidence_recency_days: 60,
    title: "Sector Rotation Tailwind",
    summary: "Macro cycle analysis suggests industrials outperformance through H2 2025.",
    details: "Fed rate trajectory and capex cycle favor sector. Position for 12-18 month hold.",
    evidence: [
      { claim: "Fed dot plot signals rate cuts", source_url: "https://federalreserve.gov", source_type: "official_document", accessed_at: "2024-12-14T09:00:00Z" },
      { claim: "Capex cycle upturn in progress", source_url: null, source_type: "economic_indicator", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["Fed follows projected path", "No recession in 2025", "Capex cycle continues"],
    falsification_criteria: ["Fed reverses to hawkish stance", "PMI drops below 45", "Credit spreads widen 100bp+"],
    source: "Macro Analysis Model",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["1Y"],
    impact_score: 0.45,
    action_required: false,
    supporting_metrics: ["Sector ETF flows", "PMI data"],
  },
  {
    id: "ai-5y-001",
    type: "analysis",
    confidence_band: "medium",
    evidence_count: 15,
    evidence_recency_days: 90,
    title: "Competitive Moat Assessment",
    summary: "Market share gains sustainable. IP portfolio and scale advantages widening.",
    details: "5-year revenue CAGR of 11.2% vs industry 6.8%. Margin differential expanding.",
    evidence: [
      { claim: "Revenue CAGR 11.2% vs industry 6.8%", source_url: null, source_type: "financial_data", accessed_at: "2024-12-14T09:00:00Z" },
      { claim: "Patent count up 23% YoY", source_url: null, source_type: "ip_database", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["Competitive dynamics stable", "Technology platform remains relevant", "Management execution continues"],
    falsification_criteria: ["Market share loss >2pp", "New entrant with disruptive technology", "Key patent expiration without replacement"],
    source: "Competitive Intelligence Engine",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["5Y", "10Y"],
    impact_score: 0.7,
    action_required: false,
    supporting_metrics: ["Market Share", "R&D Investment", "Patent Count"],
  },
  {
    id: "ai-10y-001",
    type: "analysis",
    confidence_band: "low",
    evidence_count: 6,
    evidence_recency_days: 120,
    title: "Secular Growth Runway",
    summary: "TAM expansion driven by adjacent market entry and geographic expansion.",
    details: "Long-term compounder characteristics: high ROIC, reinvestment runway, management quality.",
    evidence: [
      { claim: "ROIC consistently >20%", source_url: null, source_type: "financial_data", accessed_at: "2024-12-14T09:00:00Z" },
      { claim: "TAM expansion from $50B to $120B", source_url: null, source_type: "industry_report", accessed_at: "2024-12-14T09:00:00Z" },
    ],
    assumptions: ["TAM projections accurate", "Company captures fair share of expansion", "No technological disruption"],
    falsification_criteria: ["ROIC drops below 15%", "TAM growth stalls", "New technology obsoletes core product"],
    source: "Long-term Analysis Model",
    generated_at: "2024-12-14T09:00:00Z",
    horizon_relevance: ["10Y"],
    impact_score: 0.8,
    action_required: false,
    supporting_metrics: ["ROIC", "TAM", "Geographic Mix"],
  },
];

export const mockDashboardData: InvestorDashboard = {
  run_metadata: {
    run_id: "RUN-2024-1214-001",
    entity: "Meridian Holdings Corp",
    ticker: "MHC",
    mode: "public",
    timestamp: "2024-12-14T09:00:00Z",
    owner: "Sarah Chen, CFA",
    version: "v2.1",
    previous_run_id: "RUN-2024-1207-001",
  },

  // What Changed Since Last Run
  changes_since_last_run: [
    {
      id: "CHG-001",
      timestamp: "2024-12-12T16:00:00Z",
      category: "filing",
      title: "Q3 10-Q Filed with Raised Guidance",
      description: "Company raised FY24 revenue guidance to $3.52-3.58B from $3.45-3.52B, citing strong order book.",
      source_url: "https://sec.gov/...",
      thesis_pillar: "path",
      so_what: "Confirms operational momentum thesis. Revenue trajectory now 3% above prior model.",
      action: "Update model assumptions, consider adding to position on pullback",
      model_impact: {
        metric_affected: "FY24 Revenue",
        previous_value: "$3.48B",
        new_value: "$3.55B",
        percent_change: 2.0,
      },
    },
    {
      id: "CHG-002",
      timestamp: "2024-12-11T09:30:00Z",
      category: "price",
      title: "Stock +7.2% on Guidance Beat",
      description: "Stock rallied post-earnings, now trading at 12.4x forward EV/EBITDA vs. 11.8x prior.",
      source_url: null,
      thesis_pillar: "price",
      so_what: "Valuation gap narrowing faster than expected. Entry point less attractive.",
      action: "Trim position sizing for new capital; hold existing",
      model_impact: {
        metric_affected: "EV/EBITDA",
        previous_value: "11.8x",
        new_value: "12.4x",
        percent_change: 5.1,
      },
    },
    {
      id: "CHG-003",
      timestamp: "2024-12-10T14:00:00Z",
      category: "news",
      title: "Competitor Announces Market Exit",
      description: "Major competitor exiting industrial segment, creating $200M TAM opportunity.",
      source_url: "https://reuters.com/...",
      thesis_pillar: "path",
      so_what: "Accelerates market share thesis. Company well-positioned to capture share.",
      action: "Monitor Q4 order activity for confirmation",
      model_impact: null,
    },
    {
      id: "CHG-004",
      timestamp: "2024-12-09T11:00:00Z",
      category: "consensus",
      title: "Street Estimates Revised Higher",
      description: "4 analysts raised FY24 EPS estimates post-earnings; 1 downgrade on valuation.",
      source_url: null,
      thesis_pillar: "price",
      so_what: "Consensus catching up to our view. Less variant upside.",
      action: "Track revision momentum for next 30 days",
      model_impact: {
        metric_affected: "Consensus EPS",
        previous_value: "$4.12",
        new_value: "$4.28",
        percent_change: 3.9,
      },
    },
  ],

  executive_summary: {
    headline: "Investment thesis strengthening: operational execution exceeding plan with expanding margins and raised guidance",
    key_facts: [
      "Q3 revenue of $892M beat consensus by $36M (4.2%)",
      "EBITDA margin expanded 80bps YoY to 25.1%",
      "FY24 guidance raised: revenue $3.52-3.58B (was $3.45-3.52B)",
      "Competitor exit creates $200M addressable market opportunity",
    ],
    implications: [
      "Valuation upside of 12-18% in base case",
      "Market share gains accelerating vs. plan",
      "Operating leverage thesis proving out",
    ],
    key_risks: [
      "Customer concentration: top 3 = 34% of revenue",
      "Input cost inflation not fully passed through",
      "Management succession uncertainty (CEO age 67)",
    ],
    thesis_status: "intact",
  },

  financials: {
    revenue: createMetricWithHistory({
      value: 892000000,
      formatted: "$892M",
      unit: "USD",
      source: "10-Q Filing",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 98,
      availability: "available",
      source_reference: {
        url: "https://sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001234567",
        document_type: "filing",
        excerpt: "Total revenues for the three months ended September 30, 2024 were $892 million",
        xbrl_tag: "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
        page_reference: "Line 23, Page 5",
        accessed_at: "2024-12-14T08:00:00Z",
      },
      definition: {
        metric_name: "Revenue",
        period: "quarter",
        basis: "GAAP",
        currency: "USD",
        unit: "millions",
      },
      data_quality: {
        coverage: 100,
        auditability: 100,
        freshness_days: 0,
        overall_band: "high",
      },
      decision_context: {
        confidence_level: "high",
        sufficiency_status: "sufficient",
        knowns: ["Filed with SEC", "Auditor reviewed"],
        unknowns: [],
        what_changes_conclusion: ["Material restatement"],
      },
    }, revenueHistory),
    revenue_growth: createSimpleMetric({
      value: 12.4,
      formatted: "+12.4%",
      unit: "%",
      source: "Calculated from 10-Q",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 95,
      availability: "available",
      definition: {
        metric_name: "Revenue Growth",
        period: "quarter",
        basis: "GAAP",
        currency: null,
        unit: "percent",
        calculation_method: "(Current Quarter Revenue - Prior Year Quarter Revenue) / Prior Year Quarter Revenue",
      },
      calculation_chain: {
        formula: "(Q3 2024 Revenue - Q3 2023 Revenue) / Q3 2023 Revenue",
        formula_expanded: "($892M - $794M) / $794M = 12.4%",
        components: [
          {
            name: "Q3 2024 Revenue",
            value: 892000000,
            formatted: "$892M",
            source: "10-Q Filing Q3 2024",
            source_line: "Line 23",
            xbrl_tag: "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
            filing_date: "2024-11-15",
          },
          {
            name: "Q3 2023 Revenue",
            value: 794000000,
            formatted: "$794M",
            source: "10-Q Filing Q3 2023",
            source_line: "Line 23",
            xbrl_tag: "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
            filing_date: "2023-11-14",
          },
        ],
      },
    }),
    ebitda: createMetricWithHistory({
      value: 224000000,
      formatted: "$224M",
      unit: "USD",
      source: "Management Reconciliation",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 92,
      availability: "available",
      definition: {
        metric_name: "EBITDA",
        period: "quarter",
        basis: "non_GAAP",
        currency: "USD",
        unit: "millions",
      },
      source_reference: {
        url: "https://sec.gov/...",
        document_type: "filing",
        excerpt: "Adjusted EBITDA for Q3 2024 was $224 million",
        xbrl_tag: null,
        page_reference: "Earnings Release, Page 3",
        accessed_at: "2024-12-14T08:00:00Z",
      },
      data_quality: {
        coverage: 95,
        auditability: 88,
        freshness_days: 0,
        overall_band: "high",
      },
    }, ebitdaHistory),
    ebitda_margin: createSimpleMetric({
      value: 25.1,
      formatted: "25.1%",
      unit: "%",
      source: "Calculated",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 95,
      availability: "available",
      definition: {
        metric_name: "EBITDA Margin",
        period: "quarter",
        basis: "non_GAAP",
        currency: null,
        unit: "percent",
      },
      calculation_chain: {
        formula: "EBITDA / Revenue",
        formula_expanded: "$224M / $892M = 25.1%",
        components: [
          {
            name: "EBITDA",
            value: 224000000,
            formatted: "$224M",
            source: "Management Reconciliation",
            source_line: "Page 3",
            xbrl_tag: null,
            filing_date: "2024-11-15",
          },
          {
            name: "Revenue",
            value: 892000000,
            formatted: "$892M",
            source: "10-Q Filing",
            source_line: "Line 23",
            xbrl_tag: "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
            filing_date: "2024-11-15",
          },
        ],
      },
    }),
    free_cash_flow: createSimpleMetric({
      value: 158000000,
      formatted: "$158M",
      unit: "USD",
      source: "Cash Flow Statement",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 90,
      availability: "available",
      definition: {
        metric_name: "Free Cash Flow",
        period: "quarter",
        basis: "GAAP",
        currency: "USD",
        unit: "millions",
        calculation_method: "Cash Flow from Operations - Capital Expenditures",
      },
      calculation_chain: {
        formula: "Cash Flow from Operations - Capital Expenditures",
        formula_expanded: "$215M - $57M = $158M",
        components: [
          {
            name: "Cash Flow from Operations",
            value: 215000000,
            formatted: "$215M",
            source: "10-Q Filing, Cash Flow Statement",
            source_line: "Line 12",
            xbrl_tag: "us-gaap:NetCashProvidedByUsedInOperatingActivities",
            filing_date: "2024-11-15",
          },
          {
            name: "Capital Expenditures",
            value: 57000000,
            formatted: "$57M",
            source: "10-Q Filing, Cash Flow Statement",
            source_line: "Line 34",
            xbrl_tag: "us-gaap:PaymentsToAcquirePropertyPlantAndEquipment",
            filing_date: "2024-11-15",
          },
        ],
      },
      data_quality: {
        coverage: 100,
        auditability: 100,
        freshness_days: 0,
        overall_band: "high",
      },
    }),
  },

  market_data: {
    stock_price: createMetricWithHistory({
      value: 127.45,
      formatted: "$127.45",
      unit: "USD",
      source: "Bloomberg",
      tie_out_status: "final",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 100,
      availability: "available",
    }, stockPriceHistory),
    volume: createMetricWithHistory({
      value: 1520000,
      formatted: "1.52M",
      unit: "shares",
      source: "Bloomberg",
      tie_out_status: "final",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 98,
      availability: "available",
    }, volumeHistory),
    market_cap: createSimpleMetric({
      value: 8200000000,
      formatted: "$8.2B",
      unit: "USD",
      source: "Bloomberg",
      tie_out_status: "final",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 100,
      availability: "available",
    }),
    pe_ratio: createSimpleMetric({
      value: 18.2,
      formatted: "18.2x",
      source: "Bloomberg",
      tie_out_status: "final",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 95,
      availability: "available",
    }),
    ev_ebitda: createSimpleMetric({
      value: 11.4,
      formatted: "11.4x",
      source: "Calculated",
      tie_out_status: "final",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 88,
      availability: "available",
    }),
    target_price: createSimpleMetric({
      value: null,
      formatted: null,
      unit: "USD",
      source: "Bloomberg Consensus",
      tie_out_status: "provisional",
      last_updated: "2024-12-14T09:00:00Z",
      confidence: 0,
      availability: "pending",
      unavailable_reason: "Analyst consensus update expected after Q3 earnings cycle completes",
      decision_context: {
        confidence_level: "low",
        sufficiency_status: "insufficient",
        knowns: ["Previous target was $142"],
        unknowns: ["New analyst ratings pending"],
        what_changes_conclusion: ["Consensus publication"],
      },
    }),
  },

  private_data: {
    valuation_mark: createSimpleMetric({
      value: 850000000,
      formatted: "$850M",
      unit: "USD",
      source: "Internal Model",
      tie_out_status: "provisional",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 75,
      availability: "available",
    }),
    net_leverage: createSimpleMetric({
      value: 3.2,
      formatted: "3.2x",
      source: "Debt Schedule",
      tie_out_status: "final",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 95,
      availability: "available",
    }),
    liquidity_runway: createSimpleMetric({
      value: 18,
      formatted: "18 months",
      unit: "months",
      source: "Cash Flow Model",
      tie_out_status: "provisional",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 70,
      availability: "available",
    }),
    covenant_headroom: createSimpleMetric({
      value: null,
      formatted: null,
      source: "Credit Agreement",
      tie_out_status: "flagged",
      last_updated: "2024-12-14T08:00:00Z",
      confidence: 0,
      availability: "restricted",
      unavailable_reason: "Credit agreement amendment in progress; terms under renegotiation",
      decision_context: {
        confidence_level: "low",
        sufficiency_status: "insufficient",
        knowns: ["Renegotiation in progress"],
        unknowns: ["New covenant terms", "Timeline for closure"],
        what_changes_conclusion: ["Amendment finalization", "Lender approval"],
      },
    }),
  },

  ai_insights: hypotheses,
  hypotheses: hypotheses,

  events: [
    {
      id: "EVT-001",
      date: "2024-12-12",
      type: "earnings",
      title: "Q3 2024 Earnings Release",
      description: "Beat consensus on revenue and EPS. Management raised full-year guidance.",
      impact: "positive",
      source_url: "https://sec.gov/...",
    },
    {
      id: "EVT-002",
      date: "2024-12-10",
      type: "news",
      title: "Competitor Market Exit Announced",
      description: "Major competitor Acme Corp announces exit from North American market, creating ~$200M addressable opportunity.",
      impact: "positive",
    },
    {
      id: "EVT-003",
      date: "2024-12-05",
      type: "analyst_update",
      title: "Morgan Stanley Upgrade",
      description: "Upgraded to Overweight from Equal-weight. PT raised to $152 from $128.",
      impact: "positive",
    },
    {
      id: "EVT-004",
      date: "2024-11-28",
      type: "filing",
      title: "Form 4 - CEO Stock Sale",
      description: "CEO sold 50,000 shares at $124.50 per pre-arranged 10b5-1 plan.",
      impact: "neutral",
      source_url: "https://sec.gov/...",
    },
  ],

  scenarios: [
    {
      name: "base",
      probability: 0.6,
      assumptions: [
        { key: "Revenue Growth", value: "9.2%" },
        { key: "EBITDA Margin", value: "25.5%" },
        { key: "Multiple", value: "12.0x EV/EBITDA" },
      ],
      outputs: {
        revenue: {
          value: 3550000000,
          formatted: "$3.55B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 85,
          availability: "available",
        },
        ebitda: {
          value: 905000000,
          formatted: "$905M",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 82,
          availability: "available",
        },
        valuation: {
          value: 10860000000,
          formatted: "$10.9B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 78,
          availability: "available",
        },
      },
    },
    {
      name: "downside",
      probability: 0.25,
      assumptions: [
        { key: "Revenue Growth", value: "5.0%" },
        { key: "EBITDA Margin", value: "22.0%" },
        { key: "Multiple", value: "9.0x EV/EBITDA" },
      ],
      outputs: {
        revenue: {
          value: 3400000000,
          formatted: "$3.40B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 80,
          availability: "available",
        },
        ebitda: {
          value: 748000000,
          formatted: "$748M",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 75,
          availability: "available",
        },
        valuation: {
          value: 6732000000,
          formatted: "$6.7B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 70,
          availability: "available",
        },
      },
    },
    {
      name: "upside",
      probability: 0.15,
      assumptions: [
        { key: "Revenue Growth", value: "14.0%" },
        { key: "EBITDA Margin", value: "27.0%" },
        { key: "Multiple", value: "14.0x EV/EBITDA" },
      ],
      outputs: {
        revenue: {
          value: 3700000000,
          formatted: "$3.70B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 75,
          availability: "available",
        },
        ebitda: {
          value: 999000000,
          formatted: "$999M",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 72,
          availability: "available",
        },
        valuation: {
          value: 13986000000,
          formatted: "$14.0B",
          source: "Model",
          tie_out_status: "final",
          last_updated: "2024-12-14T08:00:00Z",
          confidence: 65,
          availability: "available",
        },
      },
    },
  ],

  // Valuation Engine
  valuation: {
    valuation_range_low: 9500000000,
    valuation_range_high: 12800000000,
    valuation_range_midpoint: 11150000000,
    why_range_exists: "DCF and comps converge at $10-11B; precedent transactions suggest premium to $12-13B for strategic buyer.",
    what_breaks_it: ["Customer concentration loss", "Margin compression >300bps", "Multiple contraction to <10x"],
    what_moves_it_next: ["Q4 order book disclosure", "FY25 guidance", "M&A speculation"],
    method_weights: { dcf: 0.4, trading_comps: 0.4, precedent_transactions: 0.2 },
    dcf: {
      implied_value: 10800000000,
      implied_value_per_share: 142,
      terminal_growth_rate: 2.5,
      wacc: 9.2,
      assumptions_sourced_percent: 78,
      blockers: ["Working capital assumptions need refresh", "Terminal margin not validated"],
    },
    trading_comps: {
      implied_value_range_low: 9200000000,
      implied_value_range_high: 11500000000,
      confidence: { coverage: 85, auditability: 90, freshness_days: 1, overall_band: "high" },
      comps: [
        { company: "Industrial Corp A", ticker: "ICA", business_model_match: 85, metric_basis: "NTM", metric_type: "adjusted", ev_revenue: 2.8, ev_ebitda: 11.2, pe_ratio: 18.5, revenue_growth: 8.5, ebitda_margin: 24.0, multiple_date: "2024-12-14", market_regime: "expansion" },
        { company: "Industrial Corp B", ticker: "ICB", business_model_match: 72, metric_basis: "NTM", metric_type: "adjusted", ev_revenue: 2.5, ev_ebitda: 10.8, pe_ratio: 16.2, revenue_growth: 6.2, ebitda_margin: 22.5, multiple_date: "2024-12-14", market_regime: "expansion" },
      ],
      blockers: [],
    },
    precedent_transactions: {
      implied_value_range_low: 11000000000,
      implied_value_range_high: 14200000000,
      confidence: { coverage: 60, auditability: 75, freshness_days: 180, overall_band: "medium" },
      transactions: [
        { id: "TX-001", target: "Similar Industrial Co", acquirer: "Strategic PE", date: "2024-03-15", rationale: "Platform consolidation", asset_quality: "premium", growth_profile: "10% organic", margin_profile: "26% EBITDA", buyer_type: "financial", ev_revenue: 3.2, ev_ebitda: 13.5, premium_paid: 28, applicability_score: 75, applicability_rationale: "Similar scale, different end markets" },
      ],
      blockers: ["Limited recent transactions in sector"],
    },
  },

  risks: [
    {
      id: "RISK-001",
      category: "financial",
      title: "Customer Concentration Risk",
      description: "Top 3 customers represent 34% of revenue. Loss of any major customer would materially impact financials.",
      severity: "high",
      trigger: "Loss of top-5 customer or >20% volume decline from any",
      mitigation: "Accelerating customer diversification; targeting 5+ new enterprise accounts in FY25",
      impact_range: { eps_impact_low: -0.45, eps_impact_high: -0.85, multiple_impact_low: -1.5, multiple_impact_high: -2.5, revenue_impact_percent: -12, probability: 0.15, timing: "12-18 months" },
      leading_indicators: [
        { name: "Top 3 Revenue %", current_value: "34%", threshold: "40%", direction: "below", source_url: null },
        { name: "Customer NPS", current_value: "72", threshold: "60", direction: "above", source_url: null },
      ],
      tripwires: [
        { condition: "Single customer >15% revenue", threshold: "15%", action: "review_thesis" },
        { condition: "Customer churn >5% annually", threshold: "5%", action: "reduce_position" },
      ],
      response: { sizing_action: "Reduce position 25% if triggered", hedge_instrument: "Sector puts", exit_condition: "Customer loss confirmed" },
    },
    {
      id: "RISK-002",
      category: "operational",
      title: "Input Cost Inflation",
      description: "Raw material costs up 12% YTD. Pricing actions lag 2-3 quarters.",
      severity: "medium",
      trigger: "Gross margin compression >200bps from current levels",
      mitigation: "Long-term supply agreements under negotiation",
      impact_range: { eps_impact_low: -0.20, eps_impact_high: -0.40, multiple_impact_low: -0.5, multiple_impact_high: -1.0, revenue_impact_percent: 0, probability: 0.30, timing: "6-12 months" },
      leading_indicators: [
        { name: "PPI Industrial", current_value: "+4.2%", threshold: "+6%", direction: "below", source_url: null },
      ],
      tripwires: [
        { condition: "Gross margin <38%", threshold: "38%", action: "review_thesis" },
      ],
      response: { sizing_action: "Monitor closely", hedge_instrument: null, exit_condition: null },
    },
    {
      id: "RISK-003",
      category: "governance",
      title: "CEO Succession",
      description: "CEO age 67, no announced succession plan. Key-man risk for strategic relationships.",
      severity: "medium",
      trigger: "CEO departure announcement without successor",
      mitigation: null,
      impact_range: { eps_impact_low: 0, eps_impact_high: -0.15, multiple_impact_low: -1.0, multiple_impact_high: -2.0, revenue_impact_percent: -3, probability: 0.25, timing: "24 months" },
      tripwires: [
        { condition: "CEO health issue or resignation", threshold: null, action: "review_thesis" },
      ],
      response: { sizing_action: "Reduce position 15%", hedge_instrument: null, exit_condition: "No successor within 6 months" },
    },
  ],

  sources: [
    { name: "SEC EDGAR", type: "primary", last_refresh: "2024-12-14T08:00:00Z" },
    { name: "Bloomberg Terminal", type: "primary", last_refresh: "2024-12-14T09:00:00Z" },
    { name: "Company IR", type: "secondary", last_refresh: "2024-12-13T16:00:00Z" },
    { name: "Internal Model", type: "secondary", last_refresh: "2024-12-14T07:00:00Z" },
  ],
};
