import { InvestorDashboard } from "./investor-schema";

export const mockDashboardData: InvestorDashboard = {
  run_metadata: {
    run_id: "RUN-2024-1214-001",
    entity: "Meridian Holdings Corp",
    entity_ticker: "MHC",
    mode: "public",
    scenario: "base",
    data_cut_timestamp: "2024-12-14T09:00:00Z",
    owner: "Sarah Chen, CFA",
    reviewer: "Michael Torres",
    publisher: undefined,
    status: "reviewed",
    immutable_hash: "a3f8c2d1e5b7...",
  },

  delta_summary: {
    prior_run_id: "RUN-2024-1207-001",
    new_events: [
      "Q3 earnings beat consensus by 4.2%",
      "Management raised FY24 guidance",
      "Competitor announced market exit",
    ],
    assumption_deltas: [
      {
        field: "Revenue Growth Rate",
        prior_value: "8.5%",
        new_value: "9.2%",
        rationale: "Revised upward post-guidance raise",
        editor: "Sarah Chen",
        timestamp: "2024-12-13T14:30:00Z",
      },
    ],
    metric_revisions: [
      {
        metric: "EBITDA Margin",
        prior: "24.3%",
        current: "25.1%",
        change_pct: 3.3,
      },
      {
        metric: "Free Cash Flow",
        prior: "$142M",
        current: "$158M",
        change_pct: 11.3,
      },
    ],
    status_changes: [
      {
        metric: "Revenue Recognition",
        from: "provisional",
        to: "final",
      },
    ],
  },

  executive_summary: {
    headline:
      "Investment thesis strengthening: operational execution exceeding plan with expanding margins and raised guidance",
    key_facts: [
      "Q3 revenue of $892M beat consensus by $36M (4.2%)",
      "EBITDA margin expanded 80bps YoY to 25.1%",
      "FY24 guidance raised: revenue $3.52-3.58B (was $3.45-3.52B)",
      "Competitor exit creates $200M addressable market opportunity",
    ],
    implications: [
      "Valuation upside of 12-18% in base case",
      "Market share gains accelerating vs. plan",
      "Operating leverage thesis proving out",
    ],
    key_risks: [
      "Customer concentration: top 3 = 34% of revenue",
      "Input cost inflation not fully passed through",
      "Management succession uncertainty (CEO age 67)",
    ],
    decisions_required: [
      "Increase position size ahead of Q4?",
      "Adjust price target to reflect raised guidance",
    ],
    investment_thesis_status: "intact",
  },

  financials: {
    revenue: {
      value: 892000000,
      formatted: "$892M",
      unit: "USD",
      primary_source: "10-Q Filing",
      secondary_sources: ["Earnings Call", "Press Release"],
      tie_out_method: "Direct reconciliation to SEC filing",
      tolerance_threshold: "0.01%",
      tie_out_status: "final",
      owner: "Sarah Chen",
      reviewer: "Michael Torres",
      last_updated: "2024-12-14T08:00:00Z",
    },
    revenue_growth: {
      value: 12.4,
      formatted: "+12.4%",
      unit: "%",
      primary_source: "Calculated from 10-Q",
      tie_out_method: "YoY comparison to prior 10-Q",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
    gross_margin: {
      value: 42.3,
      formatted: "42.3%",
      unit: "%",
      primary_source: "10-Q Filing",
      tie_out_method: "Gross profit / Revenue",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
    ebitda: {
      value: 224000000,
      formatted: "$224M",
      unit: "USD",
      primary_source: "Management Reconciliation",
      secondary_sources: ["10-Q Non-GAAP tables"],
      tie_out_method: "Add-back reconciliation verified",
      tolerance_threshold: "0.5%",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
    ebitda_margin: {
      value: 25.1,
      formatted: "25.1%",
      unit: "%",
      primary_source: "Calculated",
      tie_out_method: "EBITDA / Revenue",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
    free_cash_flow: {
      value: 158000000,
      formatted: "$158M",
      unit: "USD",
      primary_source: "Cash Flow Statement",
      tie_out_method: "CFO - CapEx",
      tolerance_threshold: "1%",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
    capex: {
      value: 45000000,
      formatted: "$45M",
      unit: "USD",
      primary_source: "Cash Flow Statement",
      tie_out_method: "Direct from 10-Q",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T08:00:00Z",
    },
  },

  public_data: {
    stock_price: {
      value: 127.45,
      formatted: "$127.45",
      unit: "USD",
      primary_source: "Bloomberg",
      tie_out_method: "Real-time feed",
      tie_out_status: "final",
      owner: "System",
      last_updated: "2024-12-14T09:00:00Z",
    },
    volume: {
      value: 2340000,
      formatted: "2.34M",
      unit: "shares",
      primary_source: "Bloomberg",
      tie_out_method: "Exchange data",
      tie_out_status: "final",
      owner: "System",
      last_updated: "2024-12-14T09:00:00Z",
    },
    volatility: {
      value: 28.4,
      formatted: "28.4%",
      unit: "%",
      primary_source: "Bloomberg",
      tie_out_method: "30-day realized vol",
      tie_out_status: "final",
      owner: "System",
      last_updated: "2024-12-14T09:00:00Z",
    },
    market_cap: {
      value: 8200000000,
      formatted: "$8.2B",
      unit: "USD",
      primary_source: "Bloomberg",
      tie_out_method: "Price × Shares Outstanding",
      tie_out_status: "final",
      owner: "System",
      last_updated: "2024-12-14T09:00:00Z",
    },
    pe_ratio: {
      value: 18.2,
      formatted: "18.2x",
      primary_source: "Bloomberg",
      tie_out_method: "Price / LTM EPS",
      tie_out_status: "final",
      owner: "System",
      last_updated: "2024-12-14T09:00:00Z",
    },
    ev_ebitda: {
      value: 11.4,
      formatted: "11.4x",
      primary_source: "Calculated",
      secondary_sources: ["Bloomberg EV", "Company EBITDA"],
      tie_out_method: "EV / LTM EBITDA",
      tie_out_status: "final",
      owner: "Sarah Chen",
      last_updated: "2024-12-14T09:00:00Z",
    },
    benchmark_performance: {
      vs_index: {
        value: 8.2,
        formatted: "+8.2%",
        unit: "%",
        primary_source: "Bloomberg",
        tie_out_method: "YTD return vs S&P 500",
        tie_out_status: "final",
        owner: "System",
        last_updated: "2024-12-14T09:00:00Z",
      },
      vs_peers: {
        value: 12.1,
        formatted: "+12.1%",
        unit: "%",
        primary_source: "Internal Peer Composite",
        tie_out_method: "YTD return vs custom peer index",
        tie_out_status: "provisional",
        owner: "Sarah Chen",
        last_updated: "2024-12-14T09:00:00Z",
      },
    },
    consensus_estimates: {
      revenue: {
        value: 3550000000,
        formatted: "$3.55B",
        unit: "USD",
        primary_source: "Bloomberg Consensus",
        tie_out_method: "Aggregated analyst estimates",
        tie_out_status: "final",
        owner: "System",
        last_updated: "2024-12-14T09:00:00Z",
      },
      eps: {
        value: 7.02,
        formatted: "$7.02",
        unit: "USD",
        primary_source: "Bloomberg Consensus",
        tie_out_method: "Aggregated analyst estimates",
        tie_out_status: "final",
        owner: "System",
        last_updated: "2024-12-14T09:00:00Z",
      },
      revisions_30d: {
        up: 4,
        down: 1,
        unchanged: 7,
      },
    },
    analyst_ratings: {
      buy: 8,
      hold: 4,
      sell: 0,
      target_price: {
        value: 145,
        formatted: "$145",
        unit: "USD",
        primary_source: "Bloomberg Consensus",
        tie_out_method: "Mean analyst target",
        tie_out_status: "final",
        owner: "System",
        last_updated: "2024-12-14T09:00:00Z",
      },
    },
  },

  events: [
    {
      id: "EVT-001",
      date: "2024-12-12",
      type: "earnings",
      title: "Q3 2024 Earnings Release",
      description:
        "Beat consensus on revenue and EPS. Management raised full-year guidance.",
      impact: "positive",
      source_url: "https://sec.gov/...",
      evidence: [
        {
          source: "SEC EDGAR",
          url: "https://sec.gov/...",
          timestamp: "2024-12-12T16:00:00Z",
          confidence: 1.0,
        },
      ],
    },
    {
      id: "EVT-002",
      date: "2024-12-10",
      type: "news",
      title: "Competitor Market Exit Announced",
      description:
        "Major competitor Acme Corp announces exit from North American market, creating ~$200M addressable opportunity.",
      impact: "positive",
      evidence: [
        {
          source: "Press Release",
          timestamp: "2024-12-10T09:00:00Z",
          confidence: 1.0,
        },
      ],
    },
    {
      id: "EVT-003",
      date: "2024-12-05",
      type: "analyst_update",
      title: "Morgan Stanley Upgrade",
      description:
        "Upgraded to Overweight from Equal-weight. PT raised to $152 from $128.",
      impact: "positive",
      evidence: [
        {
          source: "Morgan Stanley Research",
          timestamp: "2024-12-05T06:30:00Z",
          confidence: 1.0,
        },
      ],
    },
    {
      id: "EVT-004",
      date: "2024-11-28",
      type: "filing",
      title: "Form 4 - CEO Stock Sale",
      description:
        "CEO sold 50,000 shares at $124.50 per pre-arranged 10b5-1 plan.",
      impact: "neutral",
      source_url: "https://sec.gov/...",
      evidence: [
        {
          source: "SEC EDGAR",
          url: "https://sec.gov/...",
          timestamp: "2024-11-28T18:00:00Z",
          confidence: 1.0,
        },
      ],
    },
  ],

  scenarios: [
    {
      name: "base",
      probability: 0.6,
      assumptions: [
        {
          key: "Revenue Growth",
          value: "9.2%",
          rationale: "Reflects raised guidance midpoint",
        },
        {
          key: "EBITDA Margin",
          value: "25.5%",
          rationale: "Continued operating leverage",
        },
        {
          key: "Multiple",
          value: "12.0x EV/EBITDA",
          rationale: "In-line with 3-year average",
        },
      ],
      outputs: {
        revenue: {
          value: 3550000000,
          formatted: "$3.55B",
          primary_source: "Model",
          tie_out_method: "Built from assumptions",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        ebitda: {
          value: 905000000,
          formatted: "$905M",
          primary_source: "Model",
          tie_out_method: "Revenue × margin",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        valuation: {
          value: 10860000000,
          formatted: "$10.9B",
          primary_source: "Model",
          tie_out_method: "EBITDA × multiple",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
      },
    },
    {
      name: "downside",
      probability: 0.25,
      assumptions: [
        {
          key: "Revenue Growth",
          value: "5.0%",
          rationale: "Macro slowdown, delayed orders",
        },
        {
          key: "EBITDA Margin",
          value: "22.0%",
          rationale: "Margin compression from mix shift",
        },
        {
          key: "Multiple",
          value: "9.0x EV/EBITDA",
          rationale: "Multiple contraction in risk-off",
        },
      ],
      outputs: {
        revenue: {
          value: 3400000000,
          formatted: "$3.40B",
          primary_source: "Model",
          tie_out_method: "Built from assumptions",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        ebitda: {
          value: 748000000,
          formatted: "$748M",
          primary_source: "Model",
          tie_out_method: "Revenue × margin",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        valuation: {
          value: 6732000000,
          formatted: "$6.7B",
          primary_source: "Model",
          tie_out_method: "EBITDA × multiple",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
      },
    },
    {
      name: "upside",
      probability: 0.15,
      assumptions: [
        {
          key: "Revenue Growth",
          value: "14.0%",
          rationale: "Full capture of competitor exit",
        },
        {
          key: "EBITDA Margin",
          value: "27.0%",
          rationale: "Scale benefits accelerate",
        },
        {
          key: "Multiple",
          value: "14.0x EV/EBITDA",
          rationale: "Re-rate on growth acceleration",
        },
      ],
      outputs: {
        revenue: {
          value: 3700000000,
          formatted: "$3.70B",
          primary_source: "Model",
          tie_out_method: "Built from assumptions",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        ebitda: {
          value: 999000000,
          formatted: "$999M",
          primary_source: "Model",
          tie_out_method: "Revenue × margin",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
        valuation: {
          value: 13986000000,
          formatted: "$14.0B",
          primary_source: "Model",
          tie_out_method: "EBITDA × multiple",
          tie_out_status: "final",
          owner: "Sarah Chen",
          last_updated: "2024-12-14T08:00:00Z",
        },
      },
    },
  ],

  risks: [
    {
      id: "RISK-001",
      category: "operational",
      title: "Customer Concentration",
      description:
        "Top 3 customers represent 34% of revenue. Loss of any would materially impact results.",
      trigger_condition: "Loss of top customer or >20% volume reduction",
      current_distance: "No indication of churn risk currently",
      severity: "high",
      watch_metrics: ["Customer revenue mix", "Contract renewal dates", "NPS scores"],
      mitigation: "Diversification initiative targeting 28% concentration by FY25",
    },
    {
      id: "RISK-002",
      category: "market",
      title: "Input Cost Inflation",
      description:
        "Raw material costs up 12% YoY. Only 60% passed through to customers.",
      trigger_condition: "Additional 10% cost increase without pricing power",
      current_distance: "200bps of margin at risk",
      severity: "medium",
      watch_metrics: ["Input cost index", "Pricing realization", "Gross margin trend"],
    },
    {
      id: "RISK-003",
      category: "governance",
      title: "Management Succession",
      description:
        "CEO age 67 with no announced succession plan. COO departed 6 months ago.",
      trigger_condition: "Unplanned CEO departure",
      current_distance: "No immediate indication",
      severity: "medium",
      watch_metrics: ["Board composition", "Executive changes", "Insider activity"],
    },
  ],

  data_lineage: {
    sources: [
      {
        name: "SEC EDGAR",
        type: "primary",
        last_refresh: "2024-12-14T06:00:00Z",
        owner: "System",
      },
      {
        name: "Bloomberg Terminal",
        type: "primary",
        last_refresh: "2024-12-14T09:00:00Z",
        owner: "System",
      },
      {
        name: "Internal Model",
        type: "derived",
        last_refresh: "2024-12-14T08:00:00Z",
        owner: "Sarah Chen",
      },
      {
        name: "Earnings Call Transcript",
        type: "secondary",
        last_refresh: "2024-12-12T18:00:00Z",
        owner: "Research Team",
      },
    ],
    reconciliation_log: [
      {
        metric: "Q3 Revenue",
        sources_compared: ["10-Q", "Press Release", "Earnings Call"],
        variance: "0.00%",
        resolution: "All sources agree",
        timestamp: "2024-12-14T07:30:00Z",
      },
      {
        metric: "EBITDA",
        sources_compared: ["10-Q Non-GAAP", "Management Guidance"],
        variance: "0.12%",
        resolution: "Within tolerance, rounding difference",
        timestamp: "2024-12-14T07:35:00Z",
      },
    ],
  },
};
